//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gra
    {
        public int id_gry { get; set; }
        public string nazwa_gry { get; set; }
        public string producent { get; set; }
        public string kategoria_wiekowa_PEGI { get; set; }
        public string typ_gry { get; set; }
        public decimal cena { get; set; }
        public string platforma { get; set; }
    }
}
