//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sklep()
        {
            this.Sprzedawcas = new HashSet<Sprzedawca>();
        }
    
        public int id_sklepu { get; set; }
        public string nazwa_sklepu { get; set; }
        public string sposob_zakupu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedawca> Sprzedawcas { get; set; }
    }
}
