//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedawca
    {
        public int id_sprzedawcy { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int id_sklepu { get; set; }
    
        public virtual Sklep Sklep { get; set; }
    }
}
